name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Pegar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 3️⃣ Instalar dependências e build
    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    # 4️⃣ Configurar SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 5️⃣ Copiar arquivos para VPS
    - name: Copy files to VPS
      run: |
        rsync -avz --delete dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/home/administrator/deploys/portfolio


    # 6️⃣ Buildar e subir containers na VPS
    - name: Deploy Docker Compose
      run: |
        ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
        "cd /home/administrator/deploys/portfolio && docker-compose down && docker-compose up -d --build"
